apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-certificate
  namespace: jenkins
spec:
  secretName: jenkins-tls
  duration: 9125h # 1y
  renewBefore: 360h # 15d
  subject:
    organizations:
    - terop k8s
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  dnsNames:
    - jenkins.terop-kuber.com
  issuerRef:
    name: jenkins-issuer
    kind: Issuer
    group: cert-manager.io