provisioner_name: k8s-local.com/nfs
storage_class: managed-nfs-storage
label: "app: nfs-client-provisioner"

container:
  image: 
    name: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner
    tag: v4.0.0

nfs:
  server: docker1.local.com
  path: /nfs-dynamic