apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
spec:
  secretName: {{ .Release.Name }}-tls-secret
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}-issuer
  commonName: "{{ .Values.ingress.host }}"
  dnsNames:
  - "{{ .Values.ingress.host }}"