{{- if .Values.tls.enable }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
spec:
  isCA: true
  commonName: {{ .Release.Name }}-cert
  secretName: {{ .Release.Name }}-tls-secret
  privateKey:
    algoritm: ECDSA
    size: 2048 
  issuerRef:
    name: {{ .Release.Name }}-issuer
    kind: Issuer
    group: cert-manager.io
  dnsNames:
  - "{{ .Values.ingress.host }}"
{{- end }}
