{{- if .Values.tls.enable }}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
spec:
  isCA: false
  secretName: {{ .Release.Name }}-tls-secret
  issuerRef:
    name: {{ .Release.Name }}-issuer
    kind: Issuer
  dnsNames:
  - "{{ .Values.ingress.host }}"

{{- end }}
