apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      {{ .Values.selector }}

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        {{ .Values.selector }}

    spec:

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.nodeAffinity.key }}
                operator: In
                values:
                  -{{ .Values.nodeAffinity.values | indent 2 }}

      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.container.image.name }}:{{ .Values.container.image.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}

{{- if .Values.volumes.data.enable }}
          volumeMounts:
          - name: {{ .Release.Name }}-volume
            mountPath: {{ .Values.volumes.data.mountPath }}

      volumes:
      - name: {{ .Release.Name }}-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
{{- end }}
