{{- if .Values.volumes.data.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc

spec:
  storageClassName: {{ .Values.volumes.data.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.data.storage }}
{{- end }}