apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{ .Values.selector }}

spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port.port_number }}
    targetPort: {{ .Values.container.port }}
    name: {{ .Values.service.port.port_name }}
  selector:
    {{ .Values.selector }}