---
- name: Install NFS Client
  apt:
    name: nfs-common
    state: present

- name: Create Mount Point
  file:
    path: "{{ mount_point_path }}"
    state: directory

- name: Mount Remote NFS Share
  mount:
    path: "{{ mount_point_path }}"
    src: "{{ nfs_server_address }}:/{{ nfs_share }}"
    fstype: nfs
    opts: rw
    state: mounted