external_ports:
  http: 30080
  https: 30443

images: 
  ingress_controller: 
    name: us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller
    tag: v0.34.0
  ingress_controller_admission: 
    name: docker.io/jettech/kube-webhook-certgen
    tag: v1.2.2

ingress_class: nginx

node_label: "ingress-nginx-node: enable"
