apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany

  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs01.local.com
    path: "/var/nfs"