apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    owner: yk

spec:
  type: NodePort
  selector:
    dev: repl
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32001
    protocol: TCP