selector: "dev: repl"

container:
  image: 
    name: jenkins/jenkins
    tag: 2.426.3-alpine-jdk21
  port: 8080

ingress:
  host: jenkins.terop-kuber.com
  class: nginx

volumes:
  data:
    enable: false
    storageClassName: managed-nfs-storage
    storage: 5Gi
    mountPath: /var/jenkins_home

tls:
  enable: true

nodeAffinity:
  key: jenkins-app
  value: enable